### ISSUE TITLE
Algorithms being overwritten on restore when using -s | DEBUG option

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#3] opened 2018-05-07 18:50 UTC
While testing synchronization between 2 masking engines,  I wanted to validate that something that was already on the engine (#2) was not going to get overwritten.   I started with a user created segmented algorithm that existed on both my engines, #1 & #2.   I changed that same algorithm in 2 locations only on engine #2 (the algorithm description and also added an ignore character).

I then ran a backup of engine (#1) :
dlpx-masking-initializer -f lab_bkup -H engine1 -p 8282 -u delphixAPI -P  <insert_password>  -b -g -e -m -c
I then restored the file using the following options, which should not overwrite anything:
dlpx-masking-initializer -f  lab_bkup -H engine2 -p 8282 -u delphixAPI -P <insert_password> -s -l DEBUG  

No errors were received during the execution.  The engine #2 gui shows the user created algorithm was overwritten, not the expected behavior with the -s option.   The audit trail shows a description that the the algorithms were compared and no differences were found, so it was ignored.

**Comment by slusardi01** [comment] 2018-06-19 12:44
Why is this considered an enhancement and not a bug?

**Comment by bpg130** [comment] 2018-06-19 14:04
I listed this as an enhancement because the tool is working as designed.

This enhancement will be included in the next version of this tool so it is just for bookkeeping purposes.

**Closed** 2018-06-27 15:16 UTC
Labels: enhancement
